dist: xenial
language: python
before_install:
  - sudo add-apt-repository ppa:ubuntugis/ppa -y
  - sudo apt-get update -q
  - sudo apt-get install postgis postgresql-10 postgresql-10-postgis-2.4 postgresql-10-postgis-2.4-scripts postgresql-client-10 postgresql-contrib-10 python-gdal -y
  - sudo systemctl start postgresql
addons:
  postgresql: "10"
python:
  - "3.6"
install:
  - pip install -r requirements.txt
  - pip install codecov PyYAML
env:
  global:
    - DJANGO_SETTINGS_MODULE=commons_api.tests.settings DJANGO_ALLOWED_HOSTS=localhost
    - PGPORT=5432
script: PYTHONPATH=. coverage run --source=. `which django-admin.py` test
after_success:
  - codecov
